### ISSUE TITLE
Feedback: issues and suggestions

### ISSUE THREAD

**Issue by germa89** [ansys/review-bot#97]
**I will keep posting here in the following days**

## PRs reviewed
So far the reviewer has commend in the following PRs:
* [PR1](https://github.com/ansys/pymapdl/pull/2332) https://github.com/ansys/pymapdl/pull/2332
* [PR2](https://github.com/ansys/pymapdl/pull/2349) https://github.com/ansys/pymapdl/pull/2349

## Suggestions
* The bot automatically triggered the review in https://github.com/ansys/pymapdl/pull/2349
* I believe the bot should not comment until we ask to stop. I believe it should go through the PR once (or two) and stop suggesting after. If needed, the author should be able to trigger another review. Discussed here: https://github.com/ansys/pymapdl/pull/2332#issuecomment-1727161112
* The bot should not automatically review every PR.

## Interesting or detailed bot comments:
I have referenced to comments (`Comment 1`, `Comment 2`, etc) so we can discuss here in this issue each one.

* [Comment 1](https://github.com/ansys/pymapdl/pull/2332#discussion_r1330515566) Commented also [here](https://github.com/ansys/review-bot/issues/96#issuecomment-1727259227).
* [Comment 2](https://github.com/ansys/pymapdl/pull/2332#discussion_r1330517981)
* [Comment 3](https://github.com/ansys/pymapdl/pull/2332#discussion_r1330518000)
* [Comment 4](https://github.com/ansys/pymapdl/pull/2332#discussion_r1330518011)
* [Comment 5](https://github.com/ansys/pymapdl/pull/2332#discussion_r1330518035)
* [Comment 6](https://github.com/ansys/pymapdl/pull/2332#discussion_r1330523352)
* [Comment 7](https://github.com/ansys/pymapdl/pull/2332#discussion_r1330523386)
* [Comment 8](https://github.com/ansys/pymapdl/pull/2349#discussion_r1331259721)
* [Comment 9](https://github.com/ansys/pymapdl/pull/2349#discussion_r1331259763)
* [Comment 10](https://github.com/ansys/pymapdl/pull/2349#discussion_r1331259839)
* [Comment 11](https://github.com/ansys/pymapdl/pull/2349#discussion_r1331259888)
* [Comment 12](https://github.com/ansys/pymapdl/pull/2349#discussion_r1331259977)

**Comment by RobPasMue** [comment]
This issue should go here @germa89 - it is related to the service in fact.

https://github.com/ansys-internal/review-bot-service

Please open issues in that repo. Most issues will be related to the service and not to this package.

**Comment by germa89** [comment]
Closing in favour of https://github.com/ansys-internal/review-bot-service/issues/72
